name: Generate Snake

on:
  schedule:
  
    - cron: "0 0 * * *"
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
   
      - name: Generate Snake
        uses: Platane/snk@master
        with:
          github_user_name: leaviki90
          outputs: dist/snake.svg

     
      - name: Push Snake to Repository
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true
          directory: dist
